package com.yyt.trackcar.utils;

/**
 * @ projectName:   传信鸽
 * @ packageName:   com.yyt.trackcar.utils
 * @ fileName:      CWConstant
 * @ author:        QING
 * @ createTime:    2020-02-20 16:17
 * @ describe:      TODO 常数类
 */
public interface CWConstant {

    String TYPE = "type"; // 类型
    String USERNAME = "username"; // 用户名
    String COUNTRY_NAME = "countryName"; // 国家/地区名称
    String COUNTRY_CODE = "countryCode"; // 手机区号
    String VERIFICATION_CODE = "verificationCode"; // 验证码
    String PASSWORD = "password"; // 密码
    /**
     * 登录类型: 1.邮箱  2.手机
     */
    String LOGIN_TYPE = "loginType"; // 登录类型
    String PWD_TYPE = "pwdType"; // 密码类型
    String CREATE_TIME = "create_time"; // 创建时间
    String TOKEN = "token"; // token
    String U_ID = "userId"; // 用户ID
    String IMEI = "imei"; // imei
    String NAME = "name"; // 名称
    String URL = "url"; // 地址
    String TITLE = "title"; // 标题
    String CONTENT = "content"; // 内容
    String ADDRESS = "address"; // 地址
    String MODEL = "model"; // 对象
    String LIST = "list"; // 列表
    String LANGUAGE = "languages"; // 语言
    String TIME = "time"; // 时间
    String PUSH = "push"; // 推送
    String FIRST_OPEN = "first_open"; // 第一次打开
    String FIRST_CHAT_NOTIFY = "first_chat_notify"; // 第一次打开语聊
    String SERVER_ADDR = "server_address"; // 服务器地址
    String APP_VERSION_CODE = "app_version_code"; // app版本号
    String APP_VERSION_NAME = "app_version_name"; // app版本名称
    String APP_VERSION_CONTENT = "app_version_content"; // app版本内容
    String DEVICE_SETTINGS = "device_settings"; // 设备设置
    String REMOTE_PHOTO = "remote_photo"; // 远程拍照
    /**
     * 设备类型： 1.定位器 2.鸽环 3.学生卡
     */
    String DEVICE_TYPE = "device_type"; // 设备类型
    String DEVICE_MODEL = "device_model"; // 设备型号
    String USERNAME_LOGIN = "username_login"; // 用户名
    String PASSWORD_LOGIN = "password_login"; // 密码
    String HEART_RATE_TEST = "heart_rate_test";
    String BLOOD_OXYGEN_TEST = "blood_oxygen_test";

    String CHANNEL_NAME = "com.yyt.trackcar.channel";
    String CHANNEL_DEVICE_MESSAGE_ID = "channel_device_message";
    int FIVE_MINUTES = 5 * 60 * 1000;

    String PROTOCOL_URL = "http://www.allears.com.cn/privacy_cxg.html";
    String USER_SERVICE_AGREEMENT_URL = "http://www.allears.com.cn/service_agreement.html";

    String RONG_CLOUD_APP_KEY = "";
    String RONG_CLOUD_APP_SECRET = "";

    int SUCCESS = 0;  //成功        
    int ERROR = 1;  // 操作失败 
    int NOT_RESULT = 2;  // 查询没结果
    int NOT_ONLINE = 3;  // 设备不在线
    int WAIT_ONLINE_UPDATE = 4;  //设置成功上线后设备会自动同步
    int U_ALREADY_REGED = 20;  // 账号重复注册
    int U_AUTHCODE_NOTEXIST = 21;  // 验证码不存在或者失效
    int NOTEXIST_PARAM = 22;  // 必要参数不存在！
    int U_NOT_EXIST = 23;  // 账号不存在！
    int U_PWD_ERROR = 24;  // 密码错误！
    int U_TOKEN_ERR = 25;  // Token过期
    int YU_PWD_ERROR = 26;  // 原密码错误
    int BIND_ADMIN_IS_SURE = 27;  // 等待管理员确认
    int USER_ALREADY_BIND = 28;  // 用户已经绑定过
    int USER_NOT_REQUEST_BIND = 29;  // 用户尚未请求过
    int DONTNOT_TURN_MYSELF = 30;  // 不可以转让给自己
    int DEVICE_NOT_ACTIVE = 31;  // 该设备未激活
    int DEVICE_BIND_USER_NUMBER_EIGHT = 32;  // 绑定用户超过8个
    int WATCH_NOT_REGISTER = 40;  // 手表不存在
    int USER_NOT_BIND = 41;  // 用户没绑定过
    int SERVICE_BUSY = 501;  // 服务器繁忙
    int REQUERT_TOO_BUSY = 555;  // 操作太频繁

    //    String IP = "http://testchina.lagenio.xyz:8088/watchxr";
    String SERVER_ADDRESS = "hkold.lagenio.net"; // hk.lagenio.xyz
    String SERVER_ADDRESS_AMERICA = "usaold.lagenio.net";
    String SERVER_ADDRESS_EUROPE = "europeold.lagenio.net";
    String SERVER_ADDRESS_CHINA = "chinakid.lagenio.net";
    String SERVER_ADDRESS_CHINA_TWO = "192.168.1.127:8088"; // lagenio.vip   chinakid.lagenio.net:8088
    String SERVER_ADDRESS_AMERICA_TWO = "lagenio.com.cn";
    String SERVER_ADDRESS_SECOND = "hkold.lagenio.net";
    String SERVER_ADDRESS_AMERICA_SECOND = "usaold.lagenio.net";
    String SERVER_ADDRESS_EUROPE_SECOND = "europeold.lagenio.net";
    String SERVER_ADDRESS_CHINA_SECOND = "chinaold.lagenio.net";

    boolean APP_TEST = true;
    String SERVER_IP = "http://%s:8088/watchxr";
    String SERVER_IP_SECOND = "http://%s:9088/watchxr";
    String SERVER_IP_CHINA_TWO = "http://%s/watchxr";
    String WIFI_SEPARATE = "d87ac33169474b458ab3752e424509e2"; // WIFI分隔
    String URL_USER_LOGIN = "/user/loginNew"; // 登录
    int REQUEST_URL_USER_LOGIN = 1;
    String URL_GET_AUTH_CODE = "/code/getAuthCode"; // 手机验证码
    int REQUEST_URL_GET_AUTH_CODE = 2;
    String URL_GET_MAIL_CODE = "/code/getMailCode"; // 邮箱验证码
    int REQUEST_URL_GET_MAIL_CODE = 3;
    String URL_REGISTER = "/user/register"; // 注册
    int REQUEST_URL_REGISTER = 4;
    String URL_GET_BIND_DEVICE_LIST = "/watchAppUser/getbindDeviceList"; // 用户查询绑定设备列表
    int REQUEST_URL_GET_BIND_DEVICE_LIST = 5;
    String URL_GET_IMEI_BIND_USERS = "/watchAppUser/adminGetImeibindUserList"; // 设备管理员查询  某个设备的绑定用户
    int REQUEST_URL_GET_IMEI_BIND_USERS = 6;
    String URL_BIND_DEVICE = "/watchAppUser/bindDevice"; // 绑定设备
    int REQUEST_URL_BIND_DEVICE = 7;
    String URL_FIND_PWD_MAIL_CODE = "/code/findPwdMailCode"; // 找回密码  邮箱验证码的发送
    int REQUEST_URL_FIND_PWD_MAIL_CODE = 8;
    String URL_FIND_PWD_AUTH_CODE = "/code/findPwdAuthCode"; // 找回密码  手机号验证码的发送
    int REQUEST_URL_FIND_PWD_AUTH_CODE = 9;
    String URL_FIND_PWD = "/user/findPwd"; // 找回密码
    int REQUEST_URL_FIND_PWD = 10;
    String URL_GET_LAST_LOCATION = "/location/getlast/search"; // 获取定位信息
    int REQUEST_URL_GET_LAST_LOCATION = 11;
    String URL_UPDATE_USER_PORTRAIT = "/user/updateUserInfo"; // APP用户修改头像
    int REQUEST_URL_UPDATE_USER_PORTRAIT = 12;
    String URL_UPDATE_PWD = "/user/udpatePwd"; // 用户修改密码
    int REQUEST_URL_UPDATE_PWD = 13;
    String URL_TRANSFER_ADMIN = "/watchAppUser/transferAdminGet"; // 转让管理员
    int REQUEST_URL_TRANSFER_ADMIN = 14;
    String URL_DELETE_DEVICE = "/watchAppUser/deleteDevice"; // 解绑
    int REQUEST_URL_DELETE_DEVICE = 15;
    String URL_WATCH_TRACK = "/location/watchtrack"; // 获取定位轨迹
    int REQUEST_URL_WATCH_TRACK = 16;
    String URL_ADD_WATCH_FENCE = "/security/addwatchfence"; // 增加电子围栏   学校位置也使用这个接口
    int REQUEST_URL_ADD_WATCH_FENCE = 17;
    String URL_GET_WATCH_FENCE = "/security/getwatchfence"; // 查询电子围栏列表
    int REQUEST_URL_GET_WATCH_FENCE = 18;
    String URL_UPDATE_WATCH_FENCE = "/security/updatewatchfence"; // 修改电子围栏
    int REQUEST_URL_UPDATE_WATCH_FENCE = 19;
    String URL_DELETE_WATCH_FENCE = "/security/deleteWatchfence"; // 删除电子围栏
    int REQUEST_URL_DELETE_WATCH_FENCE = 20;
    String URL_GET_WATCH_INFO = "/watchinfo/get"; // 查看宝贝资料
    int REQUEST_URL_GET_WATCH_INFO = 21;
    String URL_UPDATE_WATCH_INFO = "/watchinfo/updateBabyInfo"; // 修改宝贝资料
    int REQUEST_URL_UPDATE_WATCH_INFO = 22;
    String URL_GET_APP_VERSION = "/version/getApp"; // 获取APP最新版本信息
    int REQUEST_URL_GET_APP_VERSION = 23;
    String URL_GET_WATCH_VERSION = "/version/getWatch"; // 获取手表最新版本信息(下发使用)
    int REQUEST_URL_GET_WATCH_VERSION = 24;
    String URL_GET_INSTRANCY = "/instrancy/get"; // 获取紧急通知信息(例如服务器升级维护等)
    int REQUEST_URL_GET_INSTRANCY = 25;
    String URL_GET_WATCH_MSG = "/watchAppUser/getWatchMsg"; // 获取设备系统通知消息
    int REQUEST_URL_GET_WATCH_MSG = 26;
    String URL_GET_APP_MSG = "/watchAppUser/getAppMsg"; // 获取APP系统通知消息
    int REQUEST_URL_GET_APP_MSG = 27;
    String URL_ADMIN_AGREE_BIND = "/watchAppUser/adminAgreeBind"; // 管理员同意某个用户绑定
    int REQUEST_URL_ADMIN_AGREE_BIND = 28;
    String URL_GET_DEVICE_PHOTO = "/tk/getDevicePhoto"; //  用户获取设备拍照的图片
    int REQUEST_URL_GET_DEVICE_PHOTO = 29;
    String URL_GET_DEVICE_SMS = "/tk/getDevicemSms"; //  用户获取上报短信
    int REQUEST_URL_GET_DEVICE_SMS = 30;
    String URL_GET_DEVICE_PHONE_LOG = "/tk/getDevicemPhoneLog"; //  获取通话记录
    int REQUEST_URL_GET_DEVICE_PHONE_LOG = 31;
    String URL_GET_DEVICE_FRIEND = "/tk/getDeviceFriend"; //  获取单个设备好友接口
    int REQUEST_URL_GET_DEVICE_FRIEND = 32;
    String URL_SET_DIAL_PAD = "/app/setdialpad"; //  拨号盘的打开关闭+
    int REQUEST_URL_SET_DIAL_PAD = 33;
    String URL_GET_DIAL_PAD = "/app/getdialpad"; //  获取拨号盘状态开关
    int REQUEST_URL_GET_DIAL_PAD = 34;
    String URL_AUTOMATIC_ANSWER = "/app/automaticAnswering"; //  自动接听的打开关闭
    int REQUEST_URL_AUTOMATIC_ANSWER = 35;
    String URL_GET_AUTOMATIC_ANSWER = "/app/getAutomaticAnswering"; //  获取自动接听的状态
    int REQUEST_URL_GET_AUTOMATIC_ANSWER = 36;
    String URL_FIND_DEVICE = "/controllerDevice/find"; //  查找手表
    int REQUEST_URL_FIND_DEVICE = 37;
    String URL_CAPT_DEVICE = "/controllerDevice/capt"; //  远程监拍
    int REQUEST_URL_CAPT_DEVICE = 38;
    String URL_SET_FAMILY_WIFI = "/app/setFamilyWifi"; //  设置家庭wifi
    int REQUEST_URL_SET_FAMILY_WIFI = 39;
    String URL_GET_FAMILY_WIFI = "/app/getFamilyWifi"; //  获取家庭wifi
    int REQUEST_URL_GET_FAMILY_WIFI = 40;
    String URL_SET_ALARM_CLOCK = "/app/setAlarmClock"; //  设置闹钟
    int REQUEST_URL_SET_ALARM_CLOCK = 41;
    String URL_GET_ALARM_CLOCK = "/app/getAlarmClock"; //  获取闹钟
    int REQUEST_URL_GET_ALARM_CLOCK = 42;
    String URL_REQUEST_LOCATION = "/controllerDevice/ask/localtion"; //  请求设备定位
    int REQUEST_URL_REQUEST_LOCATION = 43;
    String URL_POWER_OFF = "/controllerDevice/poweroff"; //  关机
    int REQUEST_URL_POWER_OFF = 44;
    String URL_MONIOTR_DEVICE = "/controllerDevice/moniotr"; //  监听
    int REQUEST_URL_MONIOTR_DEVICE = 45;
    String URL_FACTORY_DEVICE = "/watchuser/factory"; //  恢复出厂设置
    int REQUEST_URL_FACTORY_DEVICE = 46;
    String URL_RESET_DEVICE = "/watchuser/reset"; //  重启
    int REQUEST_URL_RESET_DEVICE = 47;
    String URL_SET_LOST = "/controllerDevice/setLost"; //  丢失 挂失
    int REQUEST_URL_SET_LOST = 48;
    String URL_GET_LOST_PASSWORD = "/controllerDevice/getLostPassword"; //  获取设置的丢失密码
    int REQUEST_URL_GET_LOST_PASSWORD = 49;
    String URL_ALREADY_FOUND = "/controllerDevice/alreadyFound"; //  解除挂失
    int REQUEST_URL_ALREADY_FOUND = 50;
    String URL_SET_CONTACTS = "/phonebook/set"; //  设置通讯录
    int REQUEST_URL_SET_CONTACTS = 51;
    String URL_GET_CONTACTS = "/phonebook/get"; //  获取通讯录
    int REQUEST_URL_GET_CONTACTS = 52;
    String URL_SET_DISABLED_INCLASS = "/app/setDisabledInClass"; //  设置上课禁用
    int REQUEST_URL_SET_DISABLED_INCLASS = 53;
    String URL_GET_DISABLED_INCLASS = "/app/getDisabledInClass"; //  获取上课禁用
    int REQUEST_URL_GET_DISABLED_INCLASS = 54;
    String URL_UPGRADE_DEVICE = "/watchuser/upgrade"; //  下发版本升级url
    int REQUEST_URL_UPGRADE_DEVICE = 55;
    String URL_LOCATION_FREQUENCY = "/app/LocationFrequency"; //  定位频率设置
    int REQUEST_URL_LOCATION_FREQUENCY = 56;
    String URL_GET_LOCATION_FREQUENCY = "/app/getLocationFrequency"; //  获取定位频率设置
    int REQUEST_URL_GET_LOCATION_FREQUENCY = 57;
    String URL_SET_STEP_GOAL = "/app/setStepGoal"; //  设置手表目标步数  计步
    int REQUEST_URL_SET_STEP_GOAL = 58;
    String URL_GET_STEP_GOAL = "/app/getStep"; //  获取手表设置目标步数
    int REQUEST_URL_GET_STEP_GOAL = 59;
    String URL_SET_OTHER = "/app/setOther"; //  设置其他参数
    int REQUEST_URL_SET_OTHER = 60;
    String URL_GET_OTHER = "/app/getOther"; //  获取设置
    int REQUEST_URL_GET_OTHER = 61;
    String URL_UPGRADE = "/watchuser/upgrade"; //  改为wifi流量升级控制
    int REQUEST_URL_UPGRADE = 62;
    String URL_GET_UPGRADE = "/watchuser/getUpgrade"; //  获取 wifi流量升级控制
    int REQUEST_URL_GET_UPGRADE = 63;
    String URL_GET_STEP_LIST = "/api/getStepList"; //  获取最近七天的步数
    int REQUEST_URL_GET_STEP_LIST = 64;
    String URL_GET_NOTIFY_STATUS = "/sys/getNotifyStatus"; // 获取用户打开关闭 通知消息
    int REQUEST_URL_GET_NOTIFY_STATUS = 65;
    String URL_SET_NOTIFY_STATUS = "/sys/setNotifyStatus"; // 用户打开关闭 通知消息
    int REQUEST_URL_SET_NOTIFY_STATUS = 66;
    String URL_UPDATE_BIND_BABY_NAME = "/watchAppUser/updateBindBabyName"; // 修改绑定设备昵称
    int REQUEST_URL_UPDATE_BIND_BABY_NAME = 67;
    String URL_UPDATE_BIND_USER_NAME = "/watchAppUser/updateBindUserName"; // 修改绑定成员里的昵称
    int REQUEST_URL_UPDATE_BIND_USER_NAME = 68;
    String URL_REFUSE_BIND = "/watchAppUser/refuseBind"; // 管理员拒绝某个用户绑定
    int REQUEST_URL_REFUSE_BIND = 69;
    String URL_UNBIND_IMEI = "/user/unbindImei"; // 管理员解绑这个设备的所有人
    int REQUEST_URL_UNBIND_IMEI = 70;
    String URL_WAKE_DEVICE = "/controllerDevice/wakeDevice"; // 唤醒手表
    int REQUEST_URL_WAKE_DEVICE = 71;
    String URL_GET_TODAY_STEP = "/app/getTodayStep"; //  获取手表步数
    int REQUEST_URL_GET_TODAY_STEP = 72;
    String URL_SET_BABY_NAME_AND_HEAD = "/watchinfo/setBabyNameAndHead"; // 设置设备头像和昵称
    int REQUEST_URL_SET_BABY_NAME_AND_HEAD = 73;
    String URL_SET_CURE_REMIND = "/app/setCureRemind"; // 设置吃药提醒
    int REQUEST_URL_SET_CURE_REMIND = 74;
    String URL_GET_CURE_REMIND = "/app/getCureRemind"; // 获取吃药提醒设置
    int REQUEST_URL_GET_CURE_REMIND = 75;
    String URL_SET_SEDENTARY_REMIND = "/app/setSedentaryRemind"; // 设置久坐提醒
    int REQUEST_URL_SET_SEDENTARY_REMIND = 76;
    String URL_GET_SEDENTARY_REMIND = "/app/getSedentaryRemind"; // 获取久坐提醒设置
    int REQUEST_URL_GET_SEDENTARY_REMIND = 77;
    String URL_HEALTH_SET = "/heath/set"; // 健康管理状态指令下发 想主动获取
    int REQUEST_URL_HEALTH_SET = 78;
    String URL_HEART_RATE_LAST = "/heath/getLagenio01Last"; // 心率获取最新
    int REQUEST_URL_HEART_RATE_LAST = 79;
    String URL_HEART_RATE_LIST = "/heath/getLagenio01List"; // 心率获取记录
    int REQUEST_URL_HEART_RATE_LIST = 80;
    String URL_BLOOD_OXYGEN_LAST = "/heath/getLagenio02Last"; // 血氧获取最新
    int REQUEST_URL_BLOOD_OXYGEN_LAST = 81;
    String URL_BLOOD_OXYGEN_LIST = "/heath/getLagenio02List"; // 血氧获取记录
    int REQUEST_URL_BLOOD_OXYGEN_LIST = 82;
    String URL_TEMPERATURE_LAST = "/heath/getLagenio03Last"; // 体温获取最新
    int REQUEST_URL_TEMPERATURE_LAST = 83;
    String URL_TEMPERATURE_LIST = "/heath/getLagenio03List"; // 体温获取记录
    int REQUEST_URL_TEMPERATURE_LIST = 84;
    String URL_BLOOD_PRESSURE_LAST = "/heath/getLagenio04Last"; // 血压获取最新
    int REQUEST_URL_BLOOD_PRESSURE_LAST = 85;
    String URL_BLOOD_PRESSURE_LIST = "/heath/getLagenio04List"; // 血压获取记录
    int REQUEST_URL_BLOOD_PRESSURE_LIST = 86;
    String URL_GET_ALL_HEALTH = "/heath/getLastAll"; // 健康管理数据库全部获取
    int REQUEST_URL_GET_ALL_HEALTH = 87;
    String URL_GET_SEVEN_HEART_RATE = "/heath/sevenHeartRate"; // 最近七次的心率
    int REQUEST_URL_GET_SEVEN_HEART_RATE = 88;
    String URL_GET_HEART_RATE_DAY_LIST = "/heath/getLagenio01DayList"; // 心率日记录  24小时记录  小时平均心率
    int REQUEST_URL_GET_HEART_RATE_DAY_LIST = 89;
    String URL_GET_HEART_RATE_MONTH_LIST = "/heath/getLagenio01MonthList"; // 心率月平均记录
    int REQUEST_URL_GET_HEART_RATE_MONTH_LIST = 90;
    String URL_GET_SEVEN_BLOOD_OXYGEN = "/heath/sevenBloodOxygen"; // 最近七次的血氧
    int REQUEST_URL_GET_SEVEN_BLOOD_OXYGEN = 91;
    String URL_GET_SEVEN_BLOOD_PRESSURE = "/heath/sevenBloodPressure"; // 最近七次的血压
    int REQUEST_URL_GET_SEVEN_BLOOD_PRESSURE = 92;
    String URL_GET_SEVEN_STEP = "/heath/sevenStep"; // 最近七次的计步
    int REQUEST_URL_GET_SEVEN_STEP = 93;
    String URL_GET_SEVEN_TEMPERATURE = "/heath/bodyTemSeven"; // 体温获取最新7次
    int REQUEST_URL_GET_SEVEN_TEMPERATURE = 94;
    String URL_GET_HEART_RATE_WEEK_LIST = "/heath/getLagenio01WeekList"; // 心率周平均记录
    int REQUEST_URL_GET_HEART_RATE_WEEK_LIST = 95;
    String URL_SET_HEART_STATUS = "/heath//setHeartStatus"; // 连续心率测量开关设置
    int REQUEST_URL_SET_HEART_STATUS = 96;
    String URL_GET_HEART_STATUS = "/heath/getHeartStatus"; // 获取连续心率测量开关设置
    int REQUEST_URL_GET_HEART_STATUS = 97;
    String URL_GET_STEP_DAY_LIST = "/heath/getStepDayList";  // 计步日记录  24小时记录
    int REQUEST_URL_GET_STEP_DAY_LIST = 98;
    String URL_SET_FALL_OFF = "/app//setFallOff";  // 佩戴检测开关设置
    int REQUEST_URL_SET_FALL_OFF = 99;
    String URL_GET_FALL_OFF = "/app/getFallOff";  // 佩戴检测开关获取
    int REQUEST_URL_GET_FALL_OFF = 100;
    String URL_JUPHOON_SEND = "/juphoon/send"; // RTOS  APP 向设备发送聊天的接口通知设备（设备在线才发起
    int REQUEST_URL_JUPHOON_SEND = 1001;
    String URL_GET_TOKEN = "http://api-sg01.ronghub.com/user/getToken.json"; //  获取融云Token
    // 正式：api-sg01.ronghub.com 测试：api-cn.ronghub.com
    int REQUEST_URL_GET_TOKEN = 999;
    String URL_JOIN_GROUP = "http://api-sg01.ronghub.com/group/join.json"; // 加入群组
    int REQUEST_URL_JOIN_GROUP = 996;
    String URL_GET_ADDRESS = "https://maps.googleapis.com/maps/api/geocode/json?latlng=%s," +
            "%s&key=AIzaSyB_4WlLFxonqvgQzXU3oo6AhgvRQHSLAn8"; //  获取地址
    int REQUEST_URL_GET_ADDRESS = 998;
    int REQUEST_UPLOAD_IMAGE = 997; // 上传图片

    int ARRIVALHOME = 1;//到家
    int SOS = 2; //SOS
    int LOCATION = 3;//定位
    int ADDFRIEND = 4;//修改好友通讯录
    int STEP = 5;//计步上报
    int UPLOADPHOTO = 6;//图片上传
    int PHONELOG = 7;//通话记录上传
    int COST = 8;//短信上报
    int UPGRADE = 9;//设备软件升级完毕
    int MONITOR = 10;//监听
    int KB = 11;//拨号盘打开关闭
    int FAMILYWIFI = 12;//设置家庭wifi
    int FIND = 13;
    int UPLOADPHOTO_SET = 14; //请求设备上传图片
    int UPGRADE_SET = 15; //让设备远程升级
    int PHB = 16; //通讯录设置
    int ANSWER = 17; //自动接听
    int CR = 18; //定位
    int POWEROFF = 19; //关机
    int FACTORY = 20; //恢复出厂设置
    int RESET = 21; //重启
    int ALARMCLOCK = 22; //闹钟设置
    int DISABLED = 23; //上课禁用
    int FREQUENCY = 24; //定位频率设置
    int STEP_SET = 25; //计步目标步数设置
    int FENCE = 26;// 电子围栏
    int ONLINE_UPDATE = 51;// 上线更新提醒
    int MANAGER_BIND = 52;// 用户绑定已有管理员的手表 管理员收到这个推送
    int AGREE_BIND = 53;// 用户绑定 管理员同意后被通知者收到这个推送
    int LOW_ENERGY = 54;// 低电量
    int POWERSAVEMODEL = 55; //设备进入省电模式
    int REFUSE_BIND = 56;//处理绑定 拒绝
    int MANAGER_UNBIND = 57;// 解绑
    int TRANSFER_MANAGER = 58;// 转让管理员
    int OPEN_DEVICE_LOST = 59; //设备开启挂失
    int CLOSE_DEVICE_LOST = 60; //设备解除挂失
    int PASSWORD_OPEN_DEVICE = 61; //设备使用密码解锁
    int DELETE_ALL_USER_BIND = 62; //解绑全部用户
    int OTHER_PLACE_LOGIN = 63; //其他地方登录
    int DEVICE_WAKE = 65; //唤醒手表
    int DEVICE_BUSY = 66; //设备繁忙
    int DEVICE_STEP_TARGET = 68; //手表达到目标步数
    int DEVICE_CHANGE_NAME = 69; //修改昵称
    int LAGENIO_01 = 90; //健康推送 血氧
    int LAGENIO_04 = 94;//跌倒提醒
    int DEVICE_BIND = 95; //绑定设备
    int LOGIN_OUT = 96;  //退出登录
    int PRECAUTIONS  = 97; //注意事项Precautions
    int PLEASE_WAIT = 100;
    int FALL_OFF = 101;
    int AGENT_DEVICE = 102; // 经销设备管理

    int LOGIN_TYPE_PHONE = 2;
    int LOGIN_TYPE_DEVICE = 888;

    int DEVICE_TYPE_L08 = 1;
    int DEVICE_TYPE_L09 = 2;
    int DEVICE_TYPE_L10 = 3;
    int DEVICE_TYPE_L11 = 4;
    int DEVICE_TYPE_L12S = 5;
    int DEVICE_TYPE_S6 = 6;
    int DEVICE_TYPE_S7 = 7;
    int DEVICE_TYPE_S8 = 8;
    int DEVICE_TYPE_S9 = 9;
    int DEVICE_TYPE_S10 = 10;
    int DEVICE_TYPE_S11 = 11;
    int DEVICE_TYPE_S12 = 12;

    int POST_MESSAGE_FINISH = 100;  // 结束
    int POST_MESSAGE_CHANGE_DEVICE = 101;  // 切换设备
    int POST_MESSAGE_BACK_TO_MAIN = 102;  // 返回主页
    int POST_MESSAGE_TO_DEVICE_MESSAGE = 103;  // 跳转设备信息页面
    int POST_MESSAGE_TO_LOCATION = 104;  // 跳转定位信息页面
    int POST_MESSAGE_TO_BIND_MEMBER = 105;  // 跳转绑定成员信息页面
    int POST_MESSAGE_BIND_MEMBER_HANDLE = 106;  // 绑定成功处理
    int POST_MESSAGE_TO_CHAT = 107;  // 跳转到微聊页面
    int POST_MESSAGE_CLEAR_CACHE = 108;  // 清除缓存
    int POST_MESSAGE_ADD_CONTACT = 109;  // 添加联系人
    int POST_MESSAGE_REFRESH_DEVICE = 110;  // 刷新设备信息
    int POST_MESSAGE_CHANGE_DEVICE_TYPE = 111;  // 切换设备类型
    int POST_MESSAGE_UPDATE_HMS = 112;  // 更新hms
    int POST_MESSAGE_CHANGE_REFRESH_INTERVAL = 113; //更改地图刷新间隔

    int REQUEST_COUNTRY_CODE = 1000;  // 国家/地区
    int REQUEST_IMAGE = 1001;  // 请求访问相册
    int REQUEST_CONTACTS_MOBILE = 1002;  // 请求访问通讯录 手机号码
    int REQUEST_CONTACTS_SHORT_NUMBER = 1003;  // 请求访问通讯录 短号/亲情号
    int REQUEST_SELECT_NAME = 1004;  // 选择名称
    int REQUEST_GALLREY = 1005; // 相册
    int REQUEST_CAMERA = 1006; // 拍照
    int REQUEST_FORBIDDEN_TIME = 1007;  // 禁用时间
    int REQUEST_FORBIDDEN_TIME_NAME = 1008;  // 禁用时间/名称
    int REQUEST_FORBIDDEN_TIME_WEEK = 1009;  // 禁用时间/周期
    int REQUEST_TIME_DISPLAY_FORMAT = 1010;  // 时间显示格式
    int REQUEST_DIAL_PAD = 1011;  // 拨号键盘
    int REQUEST_NO_SHUTDOWN = 1012;  // 禁止关机
    int REQUEST_ALARM_CLOCK = 1013;  // 闹钟设置
    int REQUEST_DEVICE_WIFI = 1014;  // 选择WIFI
    int REQUEST_FENCE_MAP = 1015;  // 添加/编辑电子围栏
    int REQUEST_CONTACTS_ADD = 1016;  // 添加通讯录
    int REQUEST_CONTACTS_DRAG = 1017;  // 通讯录排序
    int REQUEST_CONTACTS_EDIT = 1018;  // 通讯录编辑
    int REQUEST_CONTACTS_PHONE = 1019;  // 通讯录手机号
    int REQUEST_CONTACTS_EDIT_SHORT_NUMBER = 1020;  // 通讯录编辑短号/亲情号
    int REQUEST_STEP_TARGET = 1021;  // 设置目标步数
    int REQUEST_LANGUAGE = 1022;  // 语言
    int REQUEST_SERVER_ADDR = 1023;  // 服务器地址
    int REQUEST_BIND_MEMBER_EDIT = 1024;  // 绑定成员编辑
    int REQUEST_HEALTH_RECORD = 1025;  // 健康记录
    int REQUEST_OTHER = 1888;  // 其它

    int REQUEST_PERMISSION_CAMERA = 10000; // 摄像头权限
    int REQUEST_PERMISSION_STORAGE = 10001; // 读写文件权限
    int REQUEST_PERMISSION_CONTACTS_MOBILE = 1002;  // 通讯录权限
    int REQUEST_PERMISSION_CONTACTS_SHORT_NUMBER = 1003;  // 通讯录权限
    int REQUEST_PERMISSION_MOBILE_LOCATION = 1003;  // 定位权限

    int DIALOG_UNBIND = 1; // 解除绑定
    int DIALOG_SEND_CODE = 2; // 发送验证码
    int DIALOG_INPUT_NAME = 3; // 自定义名称
    int DIALOG_LOGIN_OUT = 4; // 退出登录
    int DIALOG_CLEAR_CACHE = 5; // 清除缓存
    int DIALOG_CHANGE_MOBILE = 6; // 修改手机号码
    int DIALOG_CHANGE_SHORT_NUMBER = 7; // 修改短号/亲情号
    int DIALOG_VOICE_MONITOR = 8; // 语音监护
    int DIALOG_WIFI = 9; // 选择WIFI
    int DIALOG_REPORT_LOSS = 10; // 丢失密码
    int DIALOG_MANAGER_BIND = 11; // 请求绑定
    int DIALOG_MANAGER_TRANSFER = 12; // 转让管理员
    int DIALOG_MANAGER_BIND_SECOND = 13; // 转让管理员
    int DIALOG_INPUT_USER_NICK = 14; // 修改用户昵称
    int DIALOG_REPORT_LOSS_CLOSE = 15; // 手表挂失关闭
    int DIALOG_EQUAL_EDIT_CONTACTS = 16; // 更改编辑联系人
    int DIALOG_CLEAR_CHAT_GROUP = 17; // 清除群组聊天记录
    int DIALOG_ADD_CONTACTS = 18; // 添加联系人
    int DIALOG_DEVICE_LOST = 19; // 设备丢失
    int DIALOG_DEVICE_FIND = 20; // 设备找回
    int DIALOG_DEVICE_ACTIVE = 21; // 设备激活
    int DIALOG_DEVICE_RACE_STATUS_FIRST = 22; // 个人模式
    int DIALOG_DEVICE_RACE_STATUS_SECOND = 23; // 比赛模式

    int HANDLE_CONFIRM_ACTION = 19991; // 确认
    int HANDLE_CANCEL_ACTION = 19992; // 取消
    int HANDLE_NEUTRAL_ACTION = 19993; // 中间
    int HANDLE_INPUT_ACTION = 19994; // 输入回调
    int HANDLE_OPTIONS_PICKER_ACTION = 19995; // 选择回调
    int HANDLE_LIST_ACTION = 19996; // 列表回调

    int HOME_MAP_CENTER = 0;  // 地图中心
    int HOME_TRACK_PLAYBACK = 1;  // 轨迹回放
    int HOME_SAFE_ZONE = 2;  // 电子围栏
    int HOME_TRAIN_FLIGHT = 3;  // 训飞
    int HOME_PRESET_PARAMS = 4;  // 预约设定
    int HOME_TRAJECTORY_ANALYSIS = 5;  // 轨迹分析
    int HOME_SEARCH_DEVICE = 6;  // 搜索设备
    int HOME_DISTRIBUTION_MANAGEMENT = 7;  // 经销管理
    int HOME_SEND_ORDER = 8;  // 发送指令
    int HOME_TRIP_REPORT = 9;  // 旅程报表
    int HOME_SUMMARY_RECORD = 10;  // 历史记录
    int HOME_DEVICE_SETTING = 11;  // 设备参数
    int HOME_SYSTEM_CONFIGURE = 12;  // 系统工具
    int HOME_TRACK = 13;  // 轨迹回放
    int HOME_SEND_ORDER_PET = 14;  // 发送指令
    int HOME_SEND_COMMAND_LIST = 15;  // 发送指令列表
    int HOME_BLUE_TOOTH = 16;  // 蓝牙连接

    int MORE_UPDATE_FIRMWARE = 0;  // 手表固件升级
    int MORE_BIND_MEMBER = 1;  // 绑定成员
    int MORE_ADDRESS_BOOK = 2;  // 宝贝通讯录
    int MORE_APP_STORE = 3;  // 应用商店
    int MORE_APP_MANAGER = 4;  // 应用管理
    int MORE_ACTIVITY_SQUARE = 5;  // 活动广场
    int MORE_PHOTO_DIAL = 6;  // 相片表盘
    int MORE_SMS_COLLECTION = 7;  // 代收短信
    int MORE_WATCH_BILL = 8;  // 手表话费
    int MORE_BAN_CLASSES = 9;  // 上课禁用
    int MORE_REFUSE_STRANGERS = 10;  // 拒接陌生人
    int MORE_SCHOOL_GUARDIAN = 11;  // 上学守护
    int MORE_HOLIDAY_WATCH = 12;  // 假期守护
    int MORE_TIME_SWITCH = 13;  // 定时开关机
    int MORE_AUTOMATIC_CONNECTION = 14;  // 自动接通
    int MORE_RESERVED_ELECTRIC = 15;  // 预留电量
    int MORE_WATER_REMINDER = 16;  // 泡水提醒
    int MORE_DEVICE_WIFI = 17;  // 手表Wi-Fi
    int MORE_DEIVCE_SETTINGS = 18;  // 手表设置
    int MORE_DEIVCE_REPORT_LOSS = 19;  // 手表挂失
    int MORE_CHANGE_DEIVCE = 20;  // 换表助手
    int MORE_CHANGE_NUMBER = 21;  // 更换号码
    int MORE_MY_SERVICE = 22;  // 我的客服
    int MORE_APP_SETTINGS = 23;  // APP设置
    int MORE_BIND_AND_UNBIND = 24;  // 绑定与解绑
    int MORE_CALL_RECORD = 25;  // 通话记录
    int MORE_FENCE = 26;  // 电子围栏
    int MORE_ALARM_CLOCK = 27;  // 闹钟设置
    int MORE_REMOTE_PHOTO_TAKE = 28;  // 远程拍照
    int MORE_FIND_WATCH = 29;  // 查找手表
    int MORE_VOICE_MONITOR = 30;  // 语音监护
    int MORE_SEDENTARY_REMINDER = 31;  // 久坐提醒
    int MORE_FALL_OFF = 32;  // 脱落提醒
    int MORE_BLUE_TOOTH = 33;  // 蓝牙连接
    int MORE_MESSAGE_CENTER = 34;  // 消息中心

    int DEFAULT_LOCAL_REFRESH_INTERVAL = 120; //默认刷新间隔 120s

}
